### ISSUE TITLE
模板工程改怎么自定义呢

### ISSUE THREAD

**Issue by 9JX** [mdsb100/ytx-pod-template#1]
这个模板工程改如何自定义呢，我是直接用的cocoaPods默认的模板

**Comment by mdsb100** [comment]
@songjianboy

```
pod lib create <Pod库名称> --template-url="git@github.com:mdsb100/ytx-pod-template"
```

**Comment by 9JX** [comment]
其实想问，这个模板工程是如何配合持续集成的 :)

**Comment by mdsb100** [comment]
@songjianboy
http://www.yiqixiabigao.com/yin-ke-kong-gu-iosman-man-zu-jian-hua-kai-fa-zhi-lu/
看这个吧，还是不明白加我QQ沟通78612846

.gitlab-ci.yml 这个是gitlab跑的ci。你可以根据自己实际情况选用不同的CI。那些脚本是给你参考的，做了哪些事情。

**Comment by 9JX** [comment]
好的 ，多谢:)
