### ISSUE TITLE
目前的脚本似乎不支持多版本的静态化

### ISSUE THREAD

**Issue by xilin** [mdsb100/ytx-pod-template#2]
zip.sh直接指定了`$PROJECT_NAME.zip`，这样发布的话不同版本的包无法共存？

**Comment by mdsb100** [comment]
对的，不支持。我们静态版本永远只有最新，这样有利有弊。看你们实际需要。版本控制用源码即可。
zip命令稍加修改，带个版本号就可以了。但是你的podspec的source也要有相应的变化。

**Comment by xilin** [comment]
好的，谢谢
